apiVersion: v1
kind: ConfigMap
metadata:
  name: customer
data:
  application.properties: |
    com.redhat.developer.demos.customer.rest.PreferenceService/mp-rest/url=http://preference.$NAMESPACE:80
---
apiVersion: serving.knative.dev/v1alpha1 # Current version of Knative
kind: Service
metadata:
  name: customer
spec:
  template:
    metadata:
      name: customer-v1
      annotations:
        autoscaling.knative.dev/target: "10"
    spec:
      containers:
        - image: quay.io/dsanchor/customer:quarkus
          env:
            - name: VERSION
              value: "v1"
          volumeMounts:
            - name: configuration
              mountPath: /deployments/config
      volumes:
        - name: configuration
          configMap:
            name: customer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: preference
data:
  application.properties: |
    org.eclipse.microprofile.rest.client.propagateHeaders=baggage-user-agent
    com.redhat.developer.demos.customer.rest.RecommendationService/mp-rest/url=http://recommendation.$NAMESPACE:80
---
apiVersion: serving.knative.dev/v1alpha1 # Current version of Knative
kind: Service
metadata:
  name: preference 
  labels:
     serving.knative.dev/visibility: "cluster-local"
spec:
  template:
    metadata:
      name: preference-v1
      annotations:
        autoscaling.knative.dev/target: "10"
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
    spec:
      containers:
        - image: quay.io/dsanchor/preference:quarkus
          volumeMounts:
            - name: configuration
              mountPath: /deployments/config
      volumes:
        - name: configuration
          configMap:
            name: preference
---
apiVersion: serving.knative.dev/v1alpha1 # Current version of Knative
kind: Service
metadata:
  name: recommendation 
  labels:
     serving.knative.dev/visibility: "cluster-local"
spec:
  template:
    metadata:
      name: recommendation-v1
      annotations:
        autoscaling.knative.dev/target: "10"
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
    spec:
      containers:
        - image: quay.io/dsanchor/recommendation:vertx
          env:
            - name: VERSION
              value: "v1"
