apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lab-quarkus-user
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - 'patch'
- apiGroups:
  - "eventing.knative.dev"
  resources:
  - '*'
  verbs:
  - '*'
