PROJECT_NAME=workshops

OCP_USERNAME=user1
OCP_PASSWORD=openshift
USERID=1

WORKSHOP_NAME=lab-quarkus
#WORKSHOP_IMAGE=quay.io/cvicensa/lab-quarkus:0.1
WORKSHOP_TITLE="Quarkus Introduction"
WORKSHOP_DESCRIPTION="Get started with Quarkus"
RESOURCE_BUDGET=medium
MAX_SESSION_AGE=3600
IDLE_TIMEOUT=300

SPAWNER_APPLICATION=lab-quarkus
SPAWNER_MODE=hosted-workshop
SPAWNER_VERSION=7.0.1